title: Shihao Zhu
baseURL: https://ewardnewget.github.io/
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
hasCJKLanguage: true
build:
  writeStats: true
enableGitInfo: false
enableRobotsTXT: true
disableAliases: true
disableKinds:
- taxonomy
- term
- RSS
outputs:
  home:
  - HTML
  section:
  - HTML
imaging:
  quality: 90
timeout: 600000
markup:
  goldmark:
    renderer:
      unsafe: false
security:
  _merge: deep
sitemap:
  _merge: deep
